# MATH 210 Introduction to Mathematical Computing

## April 12, 2023

* Diagonalization
* Power method

In [37]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

## Diagonalization

In [38]:
A = np.array([[1,-2,0],[-2,1,-2],[0,-2,1]])
A

array([[ 1, -2,  0],
       [-2,  1, -2],
       [ 0, -2,  1]])

In [39]:
D,P = la.eig(A)
D = np.diag(D.real)
D

array([[ 3.82842712,  0.        ,  0.        ],
       [ 0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        , -1.82842712]])

In [40]:
P

array([[-5.00000000e-01, -7.07106781e-01,  5.00000000e-01],
       [ 7.07106781e-01, -1.21909150e-16,  7.07106781e-01],
       [-5.00000000e-01,  7.07106781e-01,  5.00000000e-01]])

In [41]:
A@A@A@A@A@A@A

array([[ 2997, -4286,  2996],
       [-4286,  5993, -4286],
       [ 2996, -4286,  2997]])

Eigenvectors of a symmetric matrix are orthogonal therefore $P^{-1} = P^T$.

In [42]:
P @ D**7 @ P.T

array([[ 2997., -4286.,  2996.],
       [-4286.,  5993., -4286.],
       [ 2996., -4286.,  2997.]])

In [46]:
N = 1000
A = 2*np.eye(N) - np.diag(np.ones(N-1),1) - np.diag(np.ones(N-1),-1) 
D,P = la.eig(A)
D = np.diag(D.real)
k = 10
Ak = P@D**k@P.T
Ak

array([[ 5.87860000e+04, -9.04400000e+04,  8.72100000e+04, ...,
        -3.36464668e-09,  2.95850146e-09, -1.73690861e-09],
       [-9.04400000e+04,  1.45996000e+05, -1.52456000e+05, ...,
         5.70204045e-09, -4.84246379e-09,  2.81338386e-09],
       [ 8.72100000e+04, -1.52456000e+05,  1.79911000e+05, ...,
        -7.23565327e-09,  5.59947105e-09, -3.10260698e-09],
       ...,
       [-3.36365908e-09,  5.70136453e-09, -7.23531398e-09, ...,
         1.79911000e+05, -1.52456000e+05,  8.72100000e+04],
       [ 2.95706626e-09, -4.84104270e-09,  5.59606403e-09, ...,
        -1.52456000e+05,  1.45996000e+05, -9.04400000e+04],
       [-1.73778610e-09,  2.81407662e-09, -3.10212028e-09, ...,
         8.72100000e+04, -9.04400000e+04,  5.87860000e+04]])

## Power Method

Let $A$ be a $n \times n$ matrix and **assume** that $A$ has $n$ linearly independent eigenvectors $\mathbf{v}_0,\dots,\mathbf{v}_{n-1}$ corresponding to eigenvalues $\lambda_0,\dots,\lambda_{n-1}$ such that $| \lambda_0 | > | \lambda_1 | \geq \cdots \geq | \lambda_{n-1}|$. The eigenvalue $\lambda_0$ is called a **dominant eigenvalue**.

Choose a random vector $\mathbf{x}_0$. Since $\mathbf{v}_0,\dots,\mathbf{v}_{n-1}$ are linearly independent, the vector $\mathbf{x}_0$ must be linear combination

$$
\mathbf{x}_0 = c_0 \mathbf{v}_0 + \cdots + c_{n-1}\mathbf{v}_{n-1}
$$

for some coefficients $c_0,\dots,c_{n-1}$.

In [47]:
def powerMethod(A,N):
    n = A.shape[0]
    xk = np.random.randn(n)
    for k in range(0,N):
        xk = A@xk
        xk = xk/np.max(np.abs(xk))
    evec = xk / la.norm(xk)
    evalue = xk.T @ A @ xk / (xk.T @ xk)
    return evalue,evec

In [48]:
A = np.array([[1,-2,0],[-2,1,-2],[0,-2,1]])
evalue,evec = powerMethod(A,100)
evalue

3.82842712474619

In [49]:
evec

array([-0.5       ,  0.70710678, -0.5       ])

In [50]:
D,P = la.eig(A)
D

array([ 3.82842712+0.j,  1.        +0.j, -1.82842712+0.j])

In [51]:
P

array([[-5.00000000e-01, -7.07106781e-01,  5.00000000e-01],
       [ 7.07106781e-01, -1.21909150e-16,  7.07106781e-01],
       [-5.00000000e-01,  7.07106781e-01,  5.00000000e-01]])